# Generated by Django 5.0.4 on 2024-04-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse_camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adresse_complète', models.CharField(max_length=200)),
                ('Pays', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_city', models.CharField(max_length=200)),
                ('client_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camping_name', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('camping_city', models.CharField(max_length=200)),
                ('camping_country', models.CharField(max_length=200)),
                ('id_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camping', to='camping.adresse_camping')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissions', models.FloatField(default=None, null=True)),
                ('vehicle', models.CharField(choices=[('Combustion engine car', 'Combustion engine car'), ('Electric engine car', 'Electric engine car'), ('Train', 'Train'), ('Bus', 'Bus')], default='voiture', max_length=200)),
                ('distance', models.FloatField(default=None, null=True)),
                ('year', models.IntegerField()),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='camping.camping')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='camping.client')),
            ],
        ),
    ]
