from .adresse_view import AdresseViewSet
from .camping_view import CampingViewSet
from .client_view import ClientViewSet
from .distance_by_mean_of_transport_view import Distance_by_mean_of_transport
from .emission_by_mean_of_transport_view import Emissions_by_mean_of_transport
from .gen_dashboard_emissions_group_view import EmmissionGroup
from .insert_new_value import Insert_value